const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT 
global.appUrl=process.env.APP_URL || ""     // put your deploy app/bot url here, for 24/7 for (render , koyeb, glitch)
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "false"  
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "false"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md-3";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07";
global.website =process.env.GURL || "https://whatsapp.com/channel/0029VagJIAr3bbVBCpEkAM07" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://i.ibb.co/TgwRyHR/Ephoto360-com-166de101e03cd7.jpg" || "https://i.ibb.co/bH1kbX0/a4c0b1af253197d4837ff6760d5b81c0.jpg" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "Made With LOVE!" 


global.devs = "" // Developer Contacts
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2250788145722";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || Math.floor(Math.random()*3)  === 1 ?  "true" : "false" ;  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "" //"https://i.ibb.co/pXyNHj8/suhail.jpg" // "image" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com/" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";

global.SESSION_ID = process.env.SESSION_ID  || "SUHAIL_17_12_05_12_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODgsXG4gICAgICAgIDU2LFxuICAgICAgICAxNzYsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTA1LFxuICAgICAgICA1NCxcbiAgICAgICAgNTksXG4gICAgICAgIDI0MixcbiAgICAgICAgMTEzLFxuICAgICAgICAyNTIsXG4gICAgICAgIDExNCxcbiAgICAgICAgOTgsXG4gICAgICAgIDI2LFxuICAgICAgICAxNjIsXG4gICAgICAgIDMsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjQ4LFxuICAgICAgICAxNzAsXG4gICAgICAgIDkxLFxuICAgICAgICAyMjAsXG4gICAgICAgIDY5LFxuICAgICAgICAyMzUsXG4gICAgICAgIDY0LFxuICAgICAgICAxMjUsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTQ3LFxuICAgICAgICAzOCxcbiAgICAgICAgMTU1LFxuICAgICAgICAxMjIsXG4gICAgICAgIDE1NSxcbiAgICAgICAgNDUsXG4gICAgICAgIDEwNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4OSxcbiAgICAgICAgNzgsXG4gICAgICAgIDEwMyxcbiAgICAgICAgOCxcbiAgICAgICAgMjQ5LFxuICAgICAgICA5NSxcbiAgICAgICAgMjA1LFxuICAgICAgICAxMjQsXG4gICAgICAgIDg4LFxuICAgICAgICA2NCxcbiAgICAgICAgMjMsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTcsXG4gICAgICAgIDQ1LFxuICAgICAgICAxMyxcbiAgICAgICAgMTE2LFxuICAgICAgICAzNixcbiAgICAgICAgMTc2LFxuICAgICAgICA5MixcbiAgICAgICAgMjE2LFxuICAgICAgICAyNSxcbiAgICAgICAgNjksXG4gICAgICAgIDExOCxcbiAgICAgICAgMjE3LFxuICAgICAgICAzMyxcbiAgICAgICAgMTczLFxuICAgICAgICAyMzQsXG4gICAgICAgIDI3LFxuICAgICAgICAyMCxcbiAgICAgICAgMTUxLFxuICAgICAgICA3NSxcbiAgICAgICAgODNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDI0MCxcbiAgICAgICAgNzQsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMjMxLFxuICAgICAgICAyMjgsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTcsXG4gICAgICAgIDUwLFxuICAgICAgICAyMzgsXG4gICAgICAgIDkyLFxuICAgICAgICA4NSxcbiAgICAgICAgMTk3LFxuICAgICAgICAyMTQsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTAsXG4gICAgICAgIDQ5LFxuICAgICAgICA3MyxcbiAgICAgICAgMTk2LFxuICAgICAgICAxMDYsXG4gICAgICAgIDY2LFxuICAgICAgICAxNTEsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMjA0LFxuICAgICAgICAxOTEsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTQyLFxuICAgICAgICA0MyxcbiAgICAgICAgNDMsXG4gICAgICAgIDg5LFxuICAgICAgICAxMDMsXG4gICAgICAgIDE5MSxcbiAgICAgICAgNzVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzEsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTg1LFxuICAgICAgICAyMixcbiAgICAgICAgMjE1LFxuICAgICAgICAyMzYsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTAzLFxuICAgICAgICA5NyxcbiAgICAgICAgNDksXG4gICAgICAgIDE1NixcbiAgICAgICAgMTE4LFxuICAgICAgICAyMTUsXG4gICAgICAgIDQwLFxuICAgICAgICA2MCxcbiAgICAgICAgMjI0LFxuICAgICAgICAyMzQsXG4gICAgICAgIDU5LFxuICAgICAgICAyLFxuICAgICAgICAzMCxcbiAgICAgICAgMjM1LFxuICAgICAgICA5NyxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyNixcbiAgICAgICAgMjAwLFxuICAgICAgICAxOTQsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTEzLFxuICAgICAgICAyMTksXG4gICAgICAgIDY2LFxuICAgICAgICAxMjUsXG4gICAgICAgIDQwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNDgsXG4gICAgICAgIDUxLFxuICAgICAgICAxOTMsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTk2LFxuICAgICAgICAyNDAsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTA2LFxuICAgICAgICAyMTUsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTEzLFxuICAgICAgICAyMjcsXG4gICAgICAgIDExMixcbiAgICAgICAgMjI1LFxuICAgICAgICA0OSxcbiAgICAgICAgMTQ3LFxuICAgICAgICAyMTMsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMyxcbiAgICAgICAgNDksXG4gICAgICAgIDgyLFxuICAgICAgICA5NyxcbiAgICAgICAgMzEsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMTEwLFxuICAgICAgICA3OCxcbiAgICAgICAgNzgsXG4gICAgICAgIDUwLFxuICAgICAgICAxMTYsXG4gICAgICAgIDc4LFxuICAgICAgICA4MixcbiAgICAgICAgMTIwXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQyLFxuICAgICAgICAzLFxuICAgICAgICAxNTQsXG4gICAgICAgIDMyLFxuICAgICAgICAxMjgsXG4gICAgICAgIDcwLFxuICAgICAgICA1MyxcbiAgICAgICAgMTU1LFxuICAgICAgICAxOCxcbiAgICAgICAgMTY5LFxuICAgICAgICAyMDUsXG4gICAgICAgIDMwLFxuICAgICAgICA5MyxcbiAgICAgICAgMzUsXG4gICAgICAgIDExMixcbiAgICAgICAgMjIyLFxuICAgICAgICAxNTIsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTQ1LFxuICAgICAgICAxNDQsXG4gICAgICAgIDE1NyxcbiAgICAgICAgNzEsXG4gICAgICAgIDI0NCxcbiAgICAgICAgNCxcbiAgICAgICAgMjE3LFxuICAgICAgICA0NSxcbiAgICAgICAgMTY0LFxuICAgICAgICA5OCxcbiAgICAgICAgMTgxLFxuICAgICAgICAxODksXG4gICAgICAgIDEyNSxcbiAgICAgICAgOTZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDI0MyxcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICA2MSxcbiAgICAgICAgICA0NixcbiAgICAgICAgICAxNzAsXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDE2OCxcbiAgICAgICAgICA5LFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAyMixcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAyMTQsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMjUwLFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMjQyLFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDkwXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEwOSxcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICA2LFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDE0LFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDEsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMTIsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDEwOSxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgNixcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDIsXG4gICAgICAgICAgMjZcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMTksXG4gICAgICAgIDcsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTI3LFxuICAgICAgICAxOTgsXG4gICAgICAgIDIwNyxcbiAgICAgICAgNDMsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTY2LFxuICAgICAgICA3OSxcbiAgICAgICAgMTQsXG4gICAgICAgIDE3OCxcbiAgICAgICAgOTEsXG4gICAgICAgIDU2LFxuICAgICAgICAxOTEsXG4gICAgICAgIDIzMixcbiAgICAgICAgMjQ1LFxuICAgICAgICAxODIsXG4gICAgICAgIDE4MCxcbiAgICAgICAgODEsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTIxLFxuICAgICAgICAxMDksXG4gICAgICAgIDksXG4gICAgICAgIDE1NSxcbiAgICAgICAgNTEsXG4gICAgICAgIDExOSxcbiAgICAgICAgNDcsXG4gICAgICAgIDUzLFxuICAgICAgICA1NyxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMTksXG4gICAgICAgIDk1LFxuICAgICAgICAyMTcsXG4gICAgICAgIDEwNyxcbiAgICAgICAgNjksXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTQsXG4gICAgICAgIDE3MSxcbiAgICAgICAgNTAsXG4gICAgICAgIDQ1LFxuICAgICAgICAxNzIsXG4gICAgICAgIDQwLFxuICAgICAgICA3LFxuICAgICAgICA3OSxcbiAgICAgICAgMzMsXG4gICAgICAgIDc2LFxuICAgICAgICAyNTIsXG4gICAgICAgIDc5LFxuICAgICAgICAxNTgsXG4gICAgICAgIDEzMCxcbiAgICAgICAgNzgsXG4gICAgICAgIDM1LFxuICAgICAgICA2LFxuICAgICAgICAxODIsXG4gICAgICAgIDkwLFxuICAgICAgICAyMDYsXG4gICAgICAgIDM3LFxuICAgICAgICAxNTgsXG4gICAgICAgIDU4LFxuICAgICAgICA2MyxcbiAgICAgICAgMjIwLFxuICAgICAgICAyNDEsXG4gICAgICAgIDEzM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogODAsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiY0Q3UUpHVGpsejlXcXZ5a21oTUROc05OeHpmc3k3YnFENlpmWktBbUwyOD1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiSDJFaXlFSGNRNm1UWjNSUk1BRk04d1wiLFxuICBcInBob25lSWRcIjogXCI0ZmUzNWIzMS1hYmJhLTQ1YzEtOWNjOC05NzlmZWQ3ODJhZjNcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMjM2LFxuICAgICAgMTM5LFxuICAgICAgMTIsXG4gICAgICAyMjgsXG4gICAgICAyMixcbiAgICAgIDUyLFxuICAgICAgMjMzLFxuICAgICAgMTgwLFxuICAgICAgODAsXG4gICAgICA5NyxcbiAgICAgIDIwMixcbiAgICAgIDIzMyxcbiAgICAgIDI1NSxcbiAgICAgIDEyLFxuICAgICAgMjI3LFxuICAgICAgMTU0LFxuICAgICAgNTAsXG4gICAgICA4OSxcbiAgICAgIDE1NixcbiAgICAgIDczXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMjYsXG4gICAgICAyMzksXG4gICAgICAyMzEsXG4gICAgICAyNTMsXG4gICAgICAxNjgsXG4gICAgICAyMjYsXG4gICAgICA0MyxcbiAgICAgIDIyNixcbiAgICAgIDcwLFxuICAgICAgNjEsXG4gICAgICAxOTcsXG4gICAgICA5NCxcbiAgICAgIDkwLFxuICAgICAgMTYyLFxuICAgICAgNTksXG4gICAgICAwLFxuICAgICAgMjAzLFxuICAgICAgMTU0LFxuICAgICAgMjQ4LFxuICAgICAgMTE4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSmljb3BrRUVQL1hpTUVHR0JFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJQMytDajhZc2k0aUFkMXhQVTlXQmRlMUJqS3gyelFZZnl6UDlhZGpSOXhRPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcImdaUlNOMVEvZFVQZVpHVmIwd01SWDEzbnk4OFZaZHhLbm5oSlpNU21ISTBJeEVLVDhuK2dwOGkraDU1K2Q1a09yWDByWjh5VExpM1FIbzAwQTUxV0RnPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcImxCbFdNUERtWUI5ak9wMUs5U2ppMGtYUm5jNTZEZ1FkV3VFZUVaV2JkUGU5K3hId25yNVBwUUJ6VDFxaEI0Qmw1aW1TdkhkUDRqaEJYSCsxQ2VVaWdBPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjI1ODgxNDU3MjI6NjdAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjI5MjI3NTU0NTAwODEwOjY3QGxpZFwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjI1ODgxNDU3MjI6NjdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICA2MyxcbiAgICAgICAgICAxMjcsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDE0MyxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMTM5LFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxMjgsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDgzLFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICA2NSxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyMDUsXG4gICAgICAgICAgNixcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgNTEsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICAyMTYsXG4gICAgICAgICAgMjA5LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAyMFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzQ3MDY5OTU2LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBQTJKXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBMkouanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJnbHJZWEgwZzZYZllZTGdnOUpzUGRKbVFWTUhCOFFHVHh3OHlyNXdOMGwwPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjY3MzEyODgsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTc0NjcxNzkyODY1M1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUEySy5qc29uIjogIntcImtleURhdGFcIjpcIllwNHM4MXB6ZmMrVlNlcXRKbzE1ZzJ0dmZWc09PditkRG9pdlNWdUpoeGM9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTEyNjczMTI4OCxcImN1cnJlbnRJbmRleFwiOjUsXCJkZXZpY2VJbmRleGVzXCI6WzAsMSw1XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBMkwuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJXd3ZFbW1UQUgvT3FRNXN3emhsaUxqYnprYmNHN2ZqcTBpQjByYytSYkhJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjY3MzEyODgsXCJjdXJyZW50SW5kZXhcIjo2LFwiZGV2aWNlSW5kZXhlc1wiOlswLDUsNl19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQTJNLmpzb24iOiAie1wia2V5RGF0YVwiOlwiQzZaT1dzMWZFd0UxT2lKVElhdTloYWdieFo3cjVuTlFXUElCaCtnWkdyTT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTI2NzMxMjg4LFwiY3VycmVudEluZGV4XCI6NyxcImRldmljZUluZGV4ZXNcIjpbMCw1LDddfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUEyTi5qc29uIjogIntcImtleURhdGFcIjpcInpEcURDUnZseXQ2OFNXTW1IMldoM2swK0ZCRUhQUVRRUCt1OUZRZDROZFU9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTEyNjczMTI4OCxcImN1cnJlbnRJbmRleFwiOjcsXCJkZXZpY2VJbmRleGVzXCI6WzAsNV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQTJPLmpzb24iOiAie1wia2V5RGF0YVwiOlwiUUlEUU15RGNYSEVXOVRIRDloV3pXVVA5cllPckxyVWlSYUsrT3pZeHhzQT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTI2NzMxMjg4LFwiY3VycmVudEluZGV4XCI6OCxcImRldmljZUluZGV4ZXNcIjpbMCw1XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBMlAuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCI1SFRISVBZQUZGUURHZjVyOW5nNWNscXB6czN4cXVZaSsxY3lpZFNKT2tNPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjY3MzEyODgsXCJjdXJyZW50SW5kZXhcIjoxMixcImRldmljZUluZGV4ZXNcIjpbMCw1XX0sXCJ0aW1lc3RhbXBcIjpcIjE3NDcwMjM2NzE2NjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBMlEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJmeTlsWEc0YkNRK3dsQ3RXeGNwalFnSzA3ZERVZ1BTRXdKK2hCNkxuTDZFPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjY3MzEyODgsXCJjdXJyZW50SW5kZXhcIjoxMyxcImRldmljZUluZGV4ZXNcIjpbMCw1XX0sXCJ0aW1lc3RhbXBcIjpcIjE3NDcwMjcxOTQ2MzdcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBMlIuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJ3VXpNMXFhd2h0YnozQU44MGhQRzdMUmNKQzNrUGxuS2UvWXdGWjd3U0ZNPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjY3MzEyODgsXCJjdXJyZW50SW5kZXhcIjoxMyxcImRldmljZUluZGV4ZXNcIjpbMCw1LDEzXX0sXCJ0aW1lc3RhbXBcIjpcIjE3NDcwMjcyMDA0MjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBMlMuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJwd1hYVkh2Q1J5OHZNRjZULzhHUGF1TjRBZ0tIYjJiOXJnOCtSemFVL25zPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjY3MzEyODgsXCJjdXJyZW50SW5kZXhcIjoxMyxcImRldmljZUluZGV4ZXNcIjpbMCwxM119LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQTJULmpzb24iOiAie1wia2V5RGF0YVwiOlwiN1dpR0ladXhoR2I1SklMRzl0MUs0TEpUTkljSEJmNzRUMm00bTRRUWJUND1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMTI2NzMxMjg4LFwiY3VycmVudEluZGV4XCI6MTQsXCJkZXZpY2VJbmRleGVzXCI6WzAsMTRdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUEyVS5qc29uIjogIntcImtleURhdGFcIjpcIklUR1ZTb1pVdExxaHJtNkJyc21pUWhqcVVvVW9TMUlrOVJsRC9OaWxKems9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTEyNjczMTI4OCxcImN1cnJlbnRJbmRleFwiOjE2LFwiZGV2aWNlSW5kZXhlc1wiOlsxNiwwLDE0XX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBMlYuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJETHkwa2V0OGtYWm9TditEYjMrM0M1dGp2SzFwTUR2eHRNNEgyaDRwbGdNPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjExMjY3MzEyODgsXCJjdXJyZW50SW5kZXhcIjoxNixcImRldmljZUluZGV4ZXNcIjpbMCwxNF19LFwidGltZXN0YW1wXCI6XCIxNzQ3MDY5MDQ3NDI3XCJ9Igp9"  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "3.0.1-developement",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ GlobalTechInfo ® 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@GlobalTechInfo"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "Suhail-MD",
  ownername:process.env.OWNER_NAME|| "Suhail:Shy<3",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
